[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']
cmds = [
    'mkdir -p bootstrap/cache',
    'mkdir -p storage/framework/{sessions,views,cache}',
    'mkdir -p storage/logs',
    'chmod -R 777 bootstrap/cache storage'
]

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader'
]

[phases.build]
cmds = [
    'npm ci',
    'npm run build'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=8000'